[package]
name = "ts-bindgen-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2", features = ["derive"] }
serde_derive_internals = "0.29.1"
quote = "1"

[dev-dependencies]
ts-bindgen = { path = "../" }
